### ISSUE TITLE
argXtract vs. ida pro

### ISSUE THREAD

**Issue by Yiruma96** [projectbtle/argXtract#2]
How about the accuracy improvement of argXtract compared to ida pro in terms of inline data identification, function boundary identification, symbolization, and parameter analysis?

**Comment by projectbtle** [comment]
We don't have access to IDA Pro. All comparisons in our paper were performed between argXtract and freely available tools only.

**Comment by projectbtle** [comment]
Closing this, as argXtract is intended to complement free RE tools only.
